# Regex para identificar e extrair padrões

Use regex quando textos seguem uma estrutura. Para uma palavra literal simples, prefira contains(..., regex=False). Regex valida o formato; não comprova que um produto ou endereço existe. r antes da string evita que Python interprete barras como escapes.

Execute as demonstrações; depois tente os exercícios antes do gabarito. Escreva dados disponíveis, resultado esperado e passos em português. Requisitos: Python 3.9 ou superior, pandas e IPython. Para fusos, o ambiente precisa de dados IANA; se houver ZoneInfoNotFoundError, instale tzdata no kernel. Não é necessário baixar datasets.

## Roteiro da professora — aula integrada de 60 minutos

Os quatro notebooks pertencem a **uma aula de aproximadamente uma hora no total**. Execute as células necessárias de cima para baixo; a agenda seleciona demonstrações, não todos os exercícios. Cada exercício tem uma resolução logo após a célula de tentativa, com resultado visível quando necessário. Os gabaritos e oficinas originais continuam disponíveis para estudo posterior.

| Tempo | Conteúdo | Material |
|---|---|---|
| 0–5 min | Texto, data e problema de negócio | Datas básico |
| 5–12 min | Ler, formatar e somar datas | Datas básico |
| 12–22 min | Fuso, UTC e mudança de dia | Datas básico |
| 22–27 min | Converter uma coluna e localizar | Datas nível 2 |
| 27–32 min | O que é regex e leitura do padrão | Regex básico |
| 32–42 min | Procurar, validar e limpar | Regex básico |
| 42–49 min | Reutilizar a regra em função | Regex básico |
| 49–55 min | Aplicar padrões a uma coluna | Regex nível 2 |
| 55–60 min | Verificação e fechamento | Perguntas do roteiro |

**Preparação:** abra os quatro arquivos antes da aula e selecione o kernel Python. Os níveis 2 precisam de pandas e IPython; a demonstração com `format="ISO8601"` requer pandas 2.0 ou superior. Teste os imports previamente. A biblioteca `zoneinfo` precisa dos dados IANA; se o ambiente não os encontrar, instale `tzdata` no kernel. Os básicos usam a biblioteca padrão, mas podem precisar desses dados de fusos.

Se houver atraso, priorize os exemplos básicos e mostre apenas as tabelas dos níveis 2, preservando os cinco minutos finais de verificação.

In [2]:
import pandas as pd
from IPython.display import display

### Aplicar a uma coluna — 49–55 minutos
“No módulo `re`, entreguei uma string. Com `.str`, aplico operações de texto à coluna.”

- `produtos["descricao"]` seleciona a coluna; `.str` dá acesso às operações de texto.
- `contains("CAM-", regex=False, na=False)` busca o texto literal e trata ausência como False. Isso não valida o código.
- `[A-Z]{3}` pede três letras maiúsculas; `\d{3}` pede três dígitos.
- `(?P<codigo>...)` cria um grupo nomeado para a coluna `codigo`; `(?P<tamanho>...)` cria outro para `tamanho`.
- `P|M|G` significa uma das três alternativas.
- `extract` devolve os trechos capturados em colunas; entradas sem correspondência aparecem como ausentes.
- `fullmatch(..., na=False)` verifica o formato completo de cada descrição.

Não entre em toda a sintaxe de grupos hoje: mostre a relação entre grupo e coluna. As três primeiras descrições são válidas. “CAM-12 tamanho M”, texto livre e ausência são inválidos para esta regra. Para extrair somente registros integralmente válidos, use a máscara `fullmatch` como no gabarito 1.

**Pergunta:** encontrar “CAM-” comprova que a descrição está correta? **Não**. A busca literal e a validação completa respondem a perguntas diferentes.

## Demo Identificação e extração
\d representa dígito; {3} exige três ocorrências; ^ e $ delimitam começo e fim. Parênteses criam grupos de extração; fullmatch exige o texto inteiro.

In [5]:
produtos = pd.DataFrame({"descricao": ["CAM-001 tamanho M","CAL-023 tamanho G","CAM-104 tamanho P","CAM-12 tamanho M","texto livre",None]})
produtos

           descricao
0  CAM-001 tamanho M
1  CAL-023 tamanho G
2  CAM-104 tamanho P
3   CAM-12 tamanho M
4        texto livre
5               None

In [6]:
print(produtos["descricao"].str.contains("CAM-", regex=False, na=False))

0     True
1    False
2     True
3     True
4    False
5    False
Name: descricao, dtype: bool

In [9]:
padrao = r"(?P<codigo>[A-Z]{3}-\d{3}) tamanho (?P<tamanho>P|M|G)"
padrao
extraidos = produtos["descricao"].str.extract(padrao)
extraidos

    codigo tamanho
0  CAM-001       M
1  CAL-023       G
2  CAM-104       P
3      NaN     NaN
4      NaN     NaN
5      NaN     NaN

In [10]:
display(produtos["descricao"].str.fullmatch(padrao, na=False))

0     True
1     True
2     True
3    False
4    False
5    False
Name: descricao, dtype: bool

In [ ]:
produtos = pd.DataFrame({"descricao": ["CAM-001 tamanho M","CAL-023 tamanho G","CAM-104 tamanho P","CAM-12 tamanho M","texto livre",None]})
print(produtos["descricao"].str.contains("CAM-", regex=False, na=False))
padrao = r"(?P<codigo>[A-Z]{3}-\d{3}) tamanho (?P<tamanho>P|M|G)"
extraidos = produtos["descricao"].str.extract(padrao)
display(extraidos)
display(produtos["descricao"].str.fullmatch(padrao, na=False))

## Exercícios

### 1 Extrair e conferir
Extraia código e tamanho somente de descrições que correspondem integralmente ao padrão. Liste registros inválidos, incluindo nulos.

Antes de programar: quais dados tenho e quais passos preciso seguir?

In [ ]:
# Sua solução aqui.

### Resolução para mostrar na aula

### 1 Extrair e conferir

Como pensar: Verificar fullmatch → extrair válidos → listar restantes.

Execute a célula abaixo depois das entradas do exercício. Leia os comentários e compare o resultado com a regra pedida. Os `assert` verificam o resultado esperado; quando passam, não mostram mensagem.

In [ ]:
valido = produtos["descricao"].str.fullmatch(padrao, na=False)
resultado = produtos.loc[valido,"descricao"].str.extract(padrao)
display(resultado)
display(produtos.loc[~valido])
assert len(resultado) == 3

### 2 Contar tamanhos
Conte produtos válidos por tamanho e códigos começando por CAM-.

Antes de programar: quais dados tenho e quais passos preciso seguir?

In [ ]:
# Sua solução aqui.

### Resolução para mostrar na aula

### 2 Contar tamanhos

Como pensar: Reutilizar extração válida → contar → filtro literal de prefixo.

Execute a célula abaixo depois das entradas do exercício. Leia os comentários e compare o resultado com a regra pedida. Os `assert` verificam o resultado esperado; quando passam, não mostram mensagem.

In [11]:
display(resultado["tamanho"].value_counts())
display(resultado.loc[resultado["codigo"].str.startswith("CAM-", na=False)])

NameError: name 'resultado' is not defined

### 3 Limpar telefone
Para ["(65) 99999-1234", "+55 11 98888-4321", None], remova caracteres não numéricos preservando ausência. Explique por que isso não valida o telefone.

Antes de programar: quais dados tenho e quais passos preciso seguir?

In [ ]:
# Sua solução aqui.

### Resolução para mostrar na aula

### 3 Limpar telefone

Como pensar: \D significa não dígito → substituir por vazio → manter nulo.

Execute a célula abaixo depois das entradas do exercício. Leia os comentários e compare o resultado com a regra pedida. Os `assert` verificam o resultado esperado; quando passam, não mostram mensagem.

In [ ]:
telefones = pd.Series(["(65) 99999-1234", "+55 11 98888-4321", None])
limpos = telefones.str.replace(r"\D", "", regex=True)
display(limpos)
assert limpos.iloc[0] == "65999991234"
assert pd.isna(limpos.iloc[2])

## Gabarito comentado

### 1 Extrair e conferir

Como pensar: Verificar fullmatch → extrair válidos → listar restantes.

In [12]:
valido = produtos["descricao"].str.fullmatch(padrao, na=False)
resultado = produtos.loc[valido,"descricao"].str.extract(padrao)
display(resultado)
display(produtos.loc[~valido])
#assert len(resultado) == 3

    codigo tamanho
0  CAM-001       M
1  CAL-023       G
2  CAM-104       P

          descricao
3  CAM-12 tamanho M
4       texto livre
5              None

### 2 Contar tamanhos

Como pensar: Reutilizar extração válida → contar → filtro literal de prefixo.

In [13]:
display(resultado["tamanho"].value_counts())
display(resultado.loc[resultado["codigo"].str.startswith("CAM-", na=False)])

tamanho
M    1
G    1
P    1
Name: count, dtype: int64

    codigo tamanho
0  CAM-001       M
2  CAM-104       P

### 3 Limpar telefone

Como pensar: \D significa não dígito → substituir por vazio → manter nulo.

In [14]:
telefones = pd.Series(["(65) 99999-1234", "+55 11 98888-4321", None])
limpos = telefones.str.replace(r"\D", "", regex=True)
display(limpos)
assert limpos.iloc[0] == "65999991234"
assert pd.isna(limpos.iloc[2])

0      65999991234
1    5511988884321
2             None
dtype: object

# Oficina de funções e reutilização

Definir prepara uma função; chamar executa seu corpo. Em notebooks, execute primeiro a célula com def. Faça os exercícios antes de consultar as soluções. As oficinas usam dados próprios e podem ser executadas após os imports.

## Demo Limpeza repetida
Temos dois campos com a mesma regra: manter somente dígitos, preservando nulos. Vamos aplicar uma função à coluna inteira.

In [15]:
celular = pd.Series(["(65) 99999-1234",None])
fixo = pd.Series(["(11) 3333-4444","(41) 2222-3333"])

## Pratique a transformação
Para cada atividade, escreva entrada → processamento → saída. Compare o código antes e depois: onde a regra fica definida? Quantos lugares precisam mudar quando ela muda? Funções não tornam todo código mais rápido; o ganho aqui é organização, reutilização e manutenção.

### 1 Crie a função da coluna

Crie limpar_telefones(coluna) e chame para celular e fixo.

In [ ]:

# Sua solução aqui.

### Resolução para mostrar na aula

### 1 Crie a função da coluna

A regra fica única; uma função sobre a Series permite usar o método str diretamente.

Execute a célula abaixo depois das entradas do exercício. Leia os comentários e compare o resultado com a regra pedida. Os `assert` verificam o resultado esperado; quando passam, não mostram mensagem.

In [16]:
def limpar_telefones(coluna):
    return coluna.str.replace(r"\D","",regex=True)

print(limpar_telefones(celular).tolist())
print(limpar_telefones(fixo).tolist())
assert limpar_telefones(celular).iloc[0] == "65999991234"
assert pd.isna(limpar_telefones(celular).iloc[1])

['65999991234', None]
['1133334444', '4122223333']

### 2 Função por texto e apply

Crie extrair_codigo(texto) usando re.fullmatch. Retorne o código ou None para nulos e formatos inválidos. Passe a função para apply.

In [17]:
import re
descricoes = pd.Series(["CAM-001 tamanho M","CAM-12 tamanho M",None])
# Sua solução aqui.

### Resolução para mostrar na aula

### 2 Função por texto e apply

Há várias etapas e tratamento de ausência, por isso def é mais claro que uma lambda longa.

Execute a célula abaixo depois das entradas do exercício. Leia os comentários e compare o resultado com a regra pedida. Os `assert` verificam o resultado esperado; quando passam, não mostram mensagem.

In [20]:
def extrair_codigo(texto):
    if pd.isna(texto):
        return None
    match = re.fullmatch(r"([A-Z]{3}-\d{3}) tamanho (P|M|G)",texto)
    return match.group(1) if match else None

codigos = descricoes.apply(extrair_codigo)
print(codigos.tolist())
assert codigos.iloc[0] == "CAM-001"
assert codigos.iloc[1:].isna().all()

['CAM-001', None, None]

## Soluções da oficina

### 1 Crie a função da coluna

A regra fica única; uma função sobre a Series permite usar o método str diretamente.

In [18]:
def limpar_telefones(coluna):
    return coluna.str.replace(r"\D","",regex=True)

print(limpar_telefones(celular).tolist())
print(limpar_telefones(fixo).tolist())
assert limpar_telefones(celular).iloc[0] == "65999991234"
assert pd.isna(limpar_telefones(celular).iloc[1])

['65999991234', None]
['1133334444', '4122223333']

### 2 Função por texto e apply

Há várias etapas e tratamento de ausência, por isso def é mais claro que uma lambda longa.

In [ ]:
def extrair_codigo(texto):
    if pd.isna(texto):
        return None
    match = re.fullmatch(r"([A-Z]{3}-\d{3}) tamanho (P|M|G)",texto)
    return match.group(1) if match else None

codigos = descricoes.apply(extrair_codigo)
print(codigos.tolist())
assert codigos.iloc[0] == "CAM-001"
assert codigos.iloc[1:].isna().all()

Referência: https://docs.python.org/3/tutorial/controlflow.html#defining-functions . lambda contém uma expressão; use def quando precisar de várias etapas, validação ou uma regra reutilizada com nome.