# Pandas passo a passo — Academia

Cada linha representa um aluno fictício. frequencia_semana é o número de visitas naquela semana; mensalidade é o valor em reais.

## Como usar


1. Na primeira parte, tente resolver sem olhar o gabarito.
2. Escreva o código nas células de código e suas explicações nas células de texto.
3. Execute as células de cima para baixo.

**Como pensar:** qual informação preciso? Qual coluna contém essa informação? Quero todas as linhas ou apenas algumas? Qual operação responde à pergunta?

Comentários iniciados por `#` não são executados. `NameError` pode indicar uma preparação não executada; `KeyError` pode indicar um nome de coluna escrito incorretamente.

## Preparação

`import pandas as pd` disponibiliza a biblioteca com o apelido `pd`. `dados` é um dicionário: cada chave vira uma coluna e cada lista fornece seus valores. `pd.DataFrame(dados)` cria a tabela; `df =` guarda essa tabela na variável `df`.

Os números à esquerda são os índices das linhas. Eles começam em zero.

In [2]:
import pandas as pd

dados = {'aluno': ['Ana', 'Bruno', 'Carla', 'Diego', 'Elisa', 'Felipe'], 'plano': ['Mensal', 'Trimestral', 'Mensal', 'Anual', 'Anual', 'Mensal'], 'mensalidade': [120, 100, 120, 80, 80, 120], 'frequencia_semana': [3, 1, 4, 2, 5, 0]}

df = pd.DataFrame(dados)
df

    aluno       plano  mensalidade  frequencia_semana
0     Ana      Mensal          120                  3
1   Bruno  Trimestral          100                  1
2   Carla      Mensal          120                  4
3   Diego       Anual           80                  2
4   Elisa       Anual           80                  5
5  Felipe      Mensal          120                  0

## Parte 1 — perguntas

Para cada questão: **preveja → escreva → execute → interprete**.

### Questão 1

Mostre as quatro primeiras linhas.

**Pense antes:** Quem aparecerá? Quantos alunos ficarão fora da visualização?

**Minha previsão:**

Escreva aqui.

Irão aparecer: Ana, Bruno, Carla e Diego e dois alunos ficarão fora: Elisa e Felipe

In [3]:
# Escreva sua solução abaixo.

df.head(4)

   aluno       plano  mensalidade  frequencia_semana
0    Ana      Mensal          120                  3
1  Bruno  Trimestral          100                  1
2  Carla      Mensal          120                  4
3  Diego       Anual           80                  2

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 2

Mostre somente os nomes dos alunos.

**Pense antes:** Qual coluna precisamos escolher?

**Minha previsão:**

Escreva aqui.

O nome de cada aluno está registrado na coluna 'aluno'

In [4]:
# Escreva sua solução abaixo.

df['aluno']

0       Ana
1     Bruno
2     Carla
3     Diego
4     Elisa
5    Felipe
Name: aluno, dtype: str

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 3

Calcule a média das mensalidades.

**Pense antes:** Qual coluna contém os valores? Média significa que todos pagam o mesmo?

**Minha previsão:**

Escreva aqui.

A coluna 'mensalidade' contém o valor pago por Mês por cada aluno de acordo com seu plano. A média significa somar o valor pago por mês por todos os alunos e dividir pela quantidade de alunos.

In [12]:
# Escreva sua solução abaixo.

media_mensalidades = df['mensalidade'].mean()

print(f"R${media_mensalidades:.2f}")

R$103.33

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 4

Mostre todos os dados dos alunos com frequência de pelo menos três visitas na semana.

**Pense antes:** Qual operador inclui exatamente três?

**Minha previsão:**

Escreva aqui.

Para mostrar os alunos que a frequencia_semana é exatamente 3 devemos utilizar == para criar a condicional

In [25]:
df[df['frequencia_semana'] >= 3]

   aluno   plano  mensalidade  frequencia_semana
0    Ana  Mensal          120                  3
2  Carla  Mensal          120                  4
4  Elisa   Anual           80                  5

In [19]:
# Escreva sua solução abaixo.

filtro = (df['frequencia_semana'] >= 3)

df[filtro]

   aluno   plano  mensalidade  frequencia_semana
0    Ana  Mensal          120                  3
2  Carla  Mensal          120                  4
4  Elisa   Anual           80                  5

In [24]:
df.query("frequencia_semana >= 3")

   aluno   plano  mensalidade  frequencia_semana
0    Ana  Mensal          120                  3
2  Carla  Mensal          120                  4
4  Elisa   Anual           80                  5

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 5

Use loc para mostrar somente os nomes dos alunos do plano Anual.

**Pense antes:** Estamos comparando um número ou um texto?

**Minha previsão:**

Escreva aqui.


Estamos comparando texto

In [31]:
# Escreva sua solução abaixo.

df.loc[df["plano"] == "Anual", "aluno"]

3    Diego
4    Elisa
Name: aluno, dtype: str

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 6

Use iloc para mostrar as três primeiras linhas e as duas primeiras colunas.

**Pense antes:** Quais posições entram? Quais colunas são as duas primeiras?

**Minha previsão:**

Escreva aqui.

In [ ]:
# Célula de código para entender a diferença entre .loc e .iloc

df.loc[0:3, ["aluno","plano"]]

   aluno       plano
0    Ana      Mensal
1  Bruno  Trimestral
2  Carla      Mensal
3  Diego       Anual

In [78]:
# Escreva sua solução abaixo.

df.iloc[0:3,[0,1]]

   aluno       plano
0    Ana      Mensal
1  Bruno  Trimestral
2  Carla      Mensal

In [79]:
df.iloc[0:3,0:2]

   aluno       plano
0    Ana      Mensal
1  Bruno  Trimestral
2  Carla      Mensal

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 7

Mostre a frequência de todos os alunos usando loc.

**Pense antes:** O que : sozinho representa?

**Minha previsão:**

Escreva aqui.

O ":" sozinho representa todos os dados do dataframe

In [ ]:
# Escreva sua solução abaixo.

df.loc[:, "frequencia_semana"]

0    3
1    1
2    4
3    2
4    5
5    0
Name: frequencia_semana, dtype: int64

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 8

Ordene os alunos da maior frequência para a menor.

**Pense antes:** Quem vem primeiro? Quem vem por último?

**Minha previsão:**

Escreva aqui.

A Elisa aparecerá como primeira linha pois é a aluna com maior frequência. E o Felipe aparacerá na última linha pois é o aluno com menor frequência

In [41]:
# Escreva sua solução abaixo.

df.sort_values(by="frequencia_semana", ascending=False)

    aluno       plano  mensalidade  frequencia_semana
4   Elisa       Anual           80                  5
2   Carla      Mensal          120                  4
0     Ana      Mensal          120                  3
3   Diego       Anual           80                  2
1   Bruno  Trimestral          100                  1
5  Felipe      Mensal          120                  0

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 9

Crie uma cópia e corrija a frequência de Felipe para uma visita.

**Pense antes:** Qual condição localiza Felipe? Qual coluna precisa mudar?

**Minha previsão:**

Escreva aqui.

df["aluno"] == "Felipe" localiza o aluno Felipe

Precia ser alterada a coluna "frequencia_semana"

In [47]:
# Escreva sua solução abaixo.

df_corrigido = df

df_corrigido.loc[df["aluno"] == "Felipe", "frequencia_semana"] = 1

df_corrigido

    aluno       plano  mensalidade  frequencia_semana
0     Ana      Mensal          120                  3
1   Bruno  Trimestral          100                  1
2   Carla      Mensal          120                  4
3   Diego       Anual           80                  2
4   Elisa       Anual           80                  5
5  Felipe      Mensal          120                  1

**Minha interpretação do resultado:**

Escreva aqui.

### Questão 10

Desafio: conte quantos alunos têm plano Mensal.

**Pense antes:** Podemos filtrar primeiro e depois contar as linhas?

**Minha previsão:**

Escreva aqui.

In [80]:
# Escreva sua solução abaixo.

qtd_plano_mensal = df.loc[df["plano"] == "Mensal", "aluno"].count()

print(f"Plano mensal: {qtd_plano_mensal} alunos")

Plano mensal: 3 alunos

In [ ]:
# alunos_mensais = df[df["plano"] == "Mensal"]
# quantidade = len(alunos_mensais)
# print(quantidade)

In [ ]:
# solução alternativa

print(f"Plano mensal: {len(df[df["plano"] == "Mensal"])} alunos")

Plano mensal: 3 alunos

**Minha interpretação do resultado:**

Escreva aqui.

## Parte 2 — resolução comentada

Compare com suas tentativas. Leia como pensar, execute o código e explique o resultado com suas palavras. Comece executando a preparação novamente.

In [ ]:
import pandas as pd

dados = {'aluno': ['Ana', 'Bruno', 'Carla', 'Diego', 'Elisa', 'Felipe'], 'plano': ['Mensal', 'Trimestral', 'Mensal', 'Anual', 'Anual', 'Mensal'], 'mensalidade': [120, 100, 120, 80, 80, 120], 'frequencia_semana': [3, 1, 4, 2, 5, 0]}

df = pd.DataFrame(dados)
df

    aluno       plano  mensalidade  frequencia_semana
0     Ana      Mensal          120                  3
1   Bruno  Trimestral          100                  1
2   Carla      Mensal          120                  4
3   Diego       Anual           80                  2
4   Elisa       Anual           80                  5
5  Felipe      Mensal          120                  0

### Resolução 1

**Pedido:** Mostre as quatro primeiras linhas.

**Como pensar:** Usamos head(4) para ver quatro linhas.

In [ ]:
df.head(4)

   aluno       plano  mensalidade  frequencia_semana
0    Ana      Mensal          120                  3
1  Bruno  Trimestral          100                  1
2  Carla      Mensal          120                  4
3  Diego       Anual           80                  2

**Resultado explicado:** Ana, Bruno, Carla e Diego aparecem. Dois alunos ficam fora da visualização, mas não são apagados.

### Resolução 2

**Pedido:** Mostre somente os nomes dos alunos.

**Como pensar:** Selecionamos a coluna aluno pelo nome.

In [ ]:
df["aluno"]

0       Ana
1     Bruno
2     Carla
3     Diego
4     Elisa
5    Felipe
Name: aluno, dtype: object

**Resultado explicado:** Aparecem Ana, Bruno, Carla, Diego, Elisa e Felipe.

### Resolução 3

**Pedido:** Calcule a média das mensalidades.

**Como pensar:** Selecionamos mensalidade e aplicamos mean().

In [ ]:
df["mensalidade"].mean()

np.float64(103.33333333333333)

**Resultado explicado:** A soma é 620; a média é aproximadamente R$ 103,33. Os alunos pagam valores diferentes.

### Resolução 4

**Pedido:** Mostre todos os dados dos alunos com frequência de pelo menos três visitas na semana.

**Como pensar:** Pelo menos três significa maior ou igual a 3. A condição seleciona as linhas.

In [ ]:
df[df["frequencia_semana"] >= 3]

   aluno   plano  mensalidade  frequencia_semana
0    Ana  Mensal          120                  3
2  Carla  Mensal          120                  4
4  Elisa   Anual           80                  5

**Resultado explicado:** Ana, Carla e Elisa aparecem.

### Resolução 5

**Pedido:** Use loc para mostrar somente os nomes dos alunos do plano Anual.

**Como pensar:** == compara cada plano com o texto Anual. Depois da vírgula escolhemos aluno.

In [ ]:
df.loc[df["plano"] == "Anual", "aluno"]

3    Diego
4    Elisa
Name: aluno, dtype: object

**Resultado explicado:** Diego e Elisa aparecem. O texto deve ser escrito como está na tabela.

### Resolução 6

**Pedido:** Use iloc para mostrar as três primeiras linhas e as duas primeiras colunas.

**Como pensar:** 0:3 seleciona posições 0, 1 e 2; 0:2 seleciona colunas 0 e 1.

In [ ]:
df.iloc[0:3, 0:2]

   aluno       plano
0    Ana      Mensal
1  Bruno  Trimestral
2  Carla      Mensal

**Resultado explicado:** Ana, Bruno e Carla aparecem nas colunas aluno e plano.

### Resolução 7

**Pedido:** Mostre a frequência de todos os alunos usando loc.

**Como pensar:** Selecionamos todas as linhas e uma coluna.

In [ ]:
df.loc[:, "frequencia_semana"]

0    3
1    1
2    4
3    2
4    5
5    0
Name: frequencia_semana, dtype: int64

**Resultado explicado:** As frequências são 3, 1, 4, 2, 5 e 0.

### Resolução 8

**Pedido:** Ordene os alunos da maior frequência para a menor.

**Como pensar:** Ordenamos pela frequência com ascending=False.

In [ ]:
df.sort_values("frequencia_semana", ascending=False)

    aluno       plano  mensalidade  frequencia_semana
4   Elisa       Anual           80                  5
2   Carla      Mensal          120                  4
0     Ana      Mensal          120                  3
3   Diego       Anual           80                  2
1   Bruno  Trimestral          100                  1
5  Felipe      Mensal          120                  0

**Resultado explicado:** Elisa, Carla, Ana, Diego, Bruno e Felipe. O resultado não substitui df.

### Resolução 9

**Pedido:** Crie uma cópia e corrija a frequência de Felipe para uma visita.

**Como pensar:** Usamos copy para criar a cópia; a condição escolhe Felipe e a atribuição altera sua frequência.

In [ ]:
df_corrigido = df.copy()
df_corrigido.loc[df_corrigido["aluno"] == "Felipe", "frequencia_semana"] = 1
df_corrigido

    aluno       plano  mensalidade  frequencia_semana
0     Ana      Mensal          120                  3
1   Bruno  Trimestral          100                  1
2   Carla      Mensal          120                  4
3   Diego       Anual           80                  2
4   Elisa       Anual           80                  5
5  Felipe      Mensal          120                  1

**Resultado explicado:** Felipe fica com frequência 1 na cópia; na original continua com 0.

### Resolução 10

**Pedido:** Desafio: conte quantos alunos têm plano Mensal.

**Como pensar:** Primeiro filtramos o plano Mensal. len de um DataFrame conta suas linhas.

In [ ]:
alunos_mensais = df[df["plano"] == "Mensal"]
quantidade = len(alunos_mensais)
print(quantidade)

3

**Resultado explicado:** São três alunos: Ana, Carla e Felipe.

## Lembretes

| Recurso | Significado |
|---|---|
| `df["coluna"]` | Seleciona uma coluna |
| `df[condicao]` | Seleciona as linhas que atendem à condição |
| `df.loc[linhas, colunas]` | Seleciona por rótulos ou condições |
| `df.iloc[linhas, colunas]` | Seleciona por posições começando em zero |
| `:` sozinho | Todas as linhas ou colunas |
| `0:3` no iloc | Posições 0, 1 e 2; exclui a posição 3 |
| `==` | Compara valores |
| `=` | Atribui um valor |

Selecionar ou mostrar um resultado não significa apagar as outras informações. A alteração de valores é feita explicitamente, como na questão 9.

Documentação: https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html